server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: ${REGISTER_WITH_EUREKA:false} #  默认为 true。设为 false，仅作为服务中心，不作为服务客户端。
    fetch-registry: ${FETCH_REGISTRY:false} # 默认为true。设为false，不从服务中心检索注册的服务。
  server:
    eviction-interval-timer-in-ms: ${EVICTION_INTERVAL_TIMEER:5000} #清理间隔（单位毫秒，默认是60*1000）
    enable-self-preservation: ${ENABLE_SELF_PRESERVATION:true} # 默认为true。设为false，关闭自我保护。
    # Eureka Server 在运行期间会去统计心跳失败比例在 15 分钟之内是否低于 85%
    renewal-percent-threshold: ${RENEWAL_PERCENT_THRESHOLD:0.1} # 默认是0.85